# Generated by Django 3.0.3 on 2021-08-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnotationTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chrom', models.CharField(max_length=10)),
                ('chromStart', models.IntegerField()),
                ('chromEnd', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('strand', models.CharField(max_length=1)),
                ('thickStart', models.IntegerField()),
                ('thickEnd', models.IntegerField()),
            ],
            options={
                'ordering': ('chrom',),
            },
        ),
    ]
