# Generated by Django 3.0.3 on 2021-08-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotationtrack',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='anotationtrack',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anotationtrack',
            name='strand',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='anotationtrack',
            name='thickEnd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anotationtrack',
            name='thickStart',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
